ideal_width = 80
match_block_trailing_comma = true
max_width = 120
newline_style = "Unix"
normalize_comments = true
struct_lit_multiline_style = "PreferSingle"
where_trailing_comma = true
tab_spaces = 2
